name: update-file-index

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC (調整可)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure script is executable
        run: |
          chmod +x ./generate_file_index.sh

      - name: Generate file_index.json
        run: |
          ./generate_file_index.sh file_index.json

      - name: Commit file_index.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # show status for debug
          git status --porcelain || true
          if git status --porcelain | grep -q '^ M file_index.json\|^A  file_index.json\|^?? file_index.json'; then
            git add file_index.json
            git commit -m "ci: update file_index.json"
            git push origin HEAD:main
          else
            echo "No changes to file_index.json"
          fi